In [1]:
# Base ------------------------------------------------------------------
import numpy as np
import pandas as pd

# Association Rules -----------------------------------------------------
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder

In [2]:
# Dataset ----------------------------------------------------------------
transactions = [['Bread','Milk','Butter','Jam','Biscuits'],
                ['Bread', 'Milk', 'Beer', 'Chips'],
                ['Jam', 'Soda', 'Milk'],
                ['Soda', 'Chips', 'Beer'],
                ['Chips', 'Bread', 'Beer', 'Milk'],
                ['Jam', 'Beer', 'Soda', 'Milk']]

In [3]:
te = TransactionEncoder()

In [4]:
# Fitting the transactions
te_fit = te.fit(transactions).transform(transactions)

In [6]:
mydata = pd.DataFrame(te_fit, columns = te.columns_)
mydata

    Beer  Biscuits  Bread  Butter  Chips    Jam   Milk   Soda
0  False      True   True    True  False   True   True  False
1   True     False   True   False   True  False   True  False
2  False     False  False   False  False   True   True   True
3   True     False  False   False   True  False  False   True
4   True     False   True   False   True  False   True  False
5   True     False  False   False  False   True   True   True

In [14]:
#Apriori algorithm
apriori_probs = apriori(mydata,min_support=.01, use_colnames=True)

#Association Rules
association_rules(apriori_probs, metric='confidence', min_threshold=.8)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Chips),(Beer),0.500000,0.666667,0.500000,1.0,1.5,0.166667,inf
1,(Biscuits),(Bread),0.166667,0.500000,0.166667,1.0,2.0,0.083333,inf
2,(Biscuits),(Butter),0.166667,0.166667,0.166667,1.0,6.0,0.138889,inf
3,(Butter),(Biscuits),0.166667,0.166667,0.166667,1.0,6.0,0.138889,inf
4,(Biscuits),(Jam),0.166667,0.500000,0.166667,1.0,2.0,0.083333,inf
...,...,...,...,...,...,...,...,...,...
141,"(Jam, Bread)","(Milk, Biscuits, Butter)",0.166667,0.166667,0.166667,1.0,6.0,0.138889,inf
142,"(Milk, Biscuits)","(Jam, Butter, Bread)",0.166667,0.166667,0.166667,1.0,6.0,0.138889,inf
143,"(Biscuits, Jam)","(Milk, Butter, Bread)",0.166667,0.166667,0.166667,1.0,6.0,0.138889,inf
144,(Butter),"(Milk, Biscuits, Jam, Bread)",0.166667,0.166667,0.166667,1.0,6.0,0.138889,inf
145,(Biscuits),"(Milk, Jam, Butter, Bread)",0.166667,0.166667,0.166667,1.0,6.0,0.138889,inf

In [15]:
association_rules(apriori_probs, metric='lift', min_threshold=2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Biscuits),(Bread),0.166667,0.500000,0.166667,1.000000,2.0,0.083333,inf
1,(Bread),(Biscuits),0.500000,0.166667,0.166667,0.333333,2.0,0.083333,1.25
2,(Biscuits),(Butter),0.166667,0.166667,0.166667,1.000000,6.0,0.138889,inf
3,(Butter),(Biscuits),0.166667,0.166667,0.166667,1.000000,6.0,0.138889,inf
4,(Biscuits),(Jam),0.166667,0.500000,0.166667,1.000000,2.0,0.083333,inf
...,...,...,...,...,...,...,...,...,...
161,"(Milk, Jam)","(Biscuits, Butter, Bread)",0.500000,0.166667,0.166667,0.333333,2.0,0.083333,1.25
162,(Butter),"(Milk, Biscuits, Jam, Bread)",0.166667,0.166667,0.166667,1.000000,6.0,0.138889,inf
163,(Bread),"(Milk, Biscuits, Jam, Butter)",0.500000,0.166667,0.166667,0.333333,2.0,0.083333,1.25
164,(Biscuits),"(Milk, Jam, Butter, Bread)",0.166667,0.166667,0.166667,1.000000,6.0,0.138889,inf
165,(Jam),"(Milk, Biscuits, Butter, Bread)",0.500000,0.166667,0.166667,0.333333,2.0,0.083333,1.25

In [16]:
association_rules(apriori_probs, metric='leverage', min_threshold=.2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(Milk, Chips)","(Beer, Bread)",0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf
1,"(Beer, Bread)","(Milk, Chips)",0.333333,0.333333,0.333333,1.0,3.0,0.222222,inf

In [17]:
association_rules(apriori_probs, metric='conviction', max_threshold=5)

TypeError: association_rules() got an unexpected keyword argument 'max_threshold'

In [18]:
association_rules?